const ADD_SUGGESTED_LIST_REQUEST = "ADD_SUGGESTED_LIST_REQUEST";
const ADD_SUGGESTED_LIST_SUCCESS = "ADD_SUGGESTED_LIST_SUCCESS";
const ADD_SUGGESTED_LIST_FAILED = "ADD_SUGGESTED_LIST_FAILED";

const GET_LAT_LANG_REQUEST = "GET_LAT_LANG_REQUEST";
const GET_LAT_LANG_SUCCESS = "GET_LAT_LANG_SUCCESS";
const GET_LAT_LANG_FAILED = "GET_LAT_LANG_FAILED";

const ADD_SELECTED_HISTORY = "ADD_SELECTED_HISTORY";
const CLEAR_LIST_PLACES = "CLEAR_LIST_PLACES";
const ADD_DUMMY_TO_REDUX = "ADD_DUMMY_TO_REDUX";

export default {
  ADD_SUGGESTED_LIST_REQUEST,
  ADD_SUGGESTED_LIST_SUCCESS,
  ADD_SUGGESTED_LIST_FAILED,

  GET_LAT_LANG_REQUEST,
  GET_LAT_LANG_SUCCESS,
  GET_LAT_LANG_FAILED,

  ADD_SELECTED_HISTORY,
  CLEAR_LIST_PLACES,
  ADD_DUMMY_TO_REDUX,
};
